apiVersion: v1
kind: Service
metadata:
  name: sum-service
  labels:
    {{- include "calc.commonLabels" . | nindent 4 }}
    app: sum-service
spec:
  type: {{ .Values.sum.service.type }}
  ports:
    - port: {{ .Values.sum.service.port }}
      targetPort: {{ .Values.sum.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: sum-service
