apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: debug
      image: ubuntu:24.04
      command: ["sleep", "36000"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
        #        seccompProfile:
        #          type: Unconfined
        #        privileged: true
        allowPrivilegeEscalation: true
